### ISSUE TITLE
CoCSharp.Proxy - Crashes due to new encryption

### ISSUE THREAD

**Issue by Project-Black** [FICTURE7/CoCSharp#57] opened 2016-02-02 20:32 UTC
Hello when ever i start my game the proxy crashes.

![image](https://cloud.githubusercontent.com/assets/17033400/12763365/fe8bea86-c9c1-11e5-9302-66a8d764776c.png)

Then when i click on server it crashes

![image](https://cloud.githubusercontent.com/assets/17033400/12763394/23cf4342-c9c2-11e5-9d97-652cd1f62ba7.png)

**Comment by devinvisible** [comment] 2016-02-03 01:07
Did you patch your libg.so?

**Comment by FICTURE7** [comment] 2016-02-03 02:50
For the proxy it looks like you did not patch your libg.so. You can find how to patch it with some unix commands [here](https://github.com/clugh/coc-proxy-csharp).

For the server, it currently does not support the latest encryption but that error message with CSV files should not happen. Thanks for notifying me, will take a look at it. :]

**Comment by maithanhtan** [comment] 2016-02-03 03:58
Hi Sir,
Can you give me the last patched libg.so file?

**Comment by devinvisible** [comment] 2016-02-03 06:01
I actually see the same error when running the proxy. Hmm.

> Done(27.4982ms)! Listening on *:9339
> Accepted new client: [::ffff:192.168.1.165]:63448
> Created new connection to game.clashofclans.com
> Acting as server with standard
>         publickey: 72f1a4a4c48e44da0c42310f800e96624e6dc6a641a9d41c3b5039d8dfadc27e
>         privatekey: 1891d401fadb51d25d3a9174d472a9f691a45b974285d47729c45c6538070d85
> [S < C] => ID:10100 Name:NewClientEncryptionMessage
> Acting as client with generated
>         publickey: 7d4adc15c2b6a9449ec06c9e5ce52665ca7a5d27028dbdda6bb370fa62c46e1e
>         privatekey: 5063dc544e1996ef9274df95382dfb42725fd0e22b7976aefe1f8eb061e3bc67
> [S > C] => ID:20100 Name:NewServerEncryptionMessage

I confirmed the supercell pub key at the offset I patched so I'm not sure what's up.

**Comment by devinvisible** [comment] 2016-02-03 06:05
My problem was I either didn't specify the adb push command correctly (forgot the filename in the last argument) or I tried to push while it was in use. Either way, works for me now - thanks!

**Comment by tc-maxx** [comment] 2016-02-03 21:43
Hi
I've patched my x86 libg.so but I get this error:
![error](https://cloud.githubusercontent.com/assets/17054281/12797973/299b2eac-cac7-11e5-977b-c58f998fe7fc.png)

Can you help me?

Thankz
maxx

**Comment by FICTURE7** [comment] 2016-02-04 11:59
Thats odd, the proxy should not be decrypting 20100. Are you sure you did not do anything wrong while setting it up?

**Comment by devinvisible** [comment] 2016-02-05 03:59
I swore I had patched mine too the first time... but after I re-pushed my patched libg.so (to the correct location) it worked without any issues. I'd help you look at this now (Webex or Google Hangout) if you had the time within the next hour.

**Comment by FICTURE7** [comment] 2016-02-05 12:11
I've patched the apk using winrar to view the assets of the original apk then I extracted libg.so from it. I took the `x86` version because am running on BlueStacks, then I patched it with the commands. You could do it using a hex editor as well. After I patched it, I dropped it back in the apk and resigned it. Not sure if the resigning is important but I did. I then uninstalled the original apk which I've downloaded from Playstore then install the patched apk.

**Comment by tc-maxx** [comment] 2016-02-05 23:27
Thank you guys :)
I was too stupid to patch the file correctly :) 
Another trouble was the wrong file permissions. Correct -> 755

**Comment by devinvisible** [comment] 2016-02-06 02:56
So is this working now tc?

I use Genymotion (similar to BlueStacks but lighter weight, imho). I installed the game and then used adb to pull the x86 libg.so. Because I'm working on CoCSharp, I just dropped libg.so onto Visual Studio and it opens it as a hex editor. I went to the appropriate offset (found https://github.com/clugh/coc-proxy/wiki/Key-Offsets) and changed the value to 72f1a4a4c48e44da0c42310f800e96624e6dc6a641a9d41c3b5039d8dfadc27e, the public key from our well-defined key-pair. I pushed libg.so back to where I grabbed it from. No apk signing or any of that was necessary. I didn't need to change the file permission either, but 755 would work. Don't typo the public key if you're writing it by hand.

**Comment by tc-maxx** [comment] 2016-02-06 12:15
Hi dev,

Yes now it works!
![running](https://cloud.githubusercontent.com/assets/17054281/12866481/2a506970-cccf-11e5-96f7-59459f87f9fa.png)

I wrote me a small universal file patcher for it.
[Libg.soPatch](https://github.com/tc-maxx/Libg.soPatch)

I pushed the file back in the bluetacks shared folder and than i moved it with root explorer to "data/data/com.supercell.clashofclans/."

**Comment by circa94** [comment] 2016-02-06 12:33
Hi tc-maxx!
Can you explain me how you patched the libg.so file? i am not able to patch it :(

**Comment by tc-maxx** [comment] 2016-02-06 12:38
@circa94:  just use the Libg.soPatch for patch it.

**Comment by circa94** [comment] 2016-02-06 12:47
i have patched the libg.so file with your tool. thank you so far!
Did i have to resign now the apk? beacause when i am try to install the apk with patched libg.so file i  run in the error: Apk Installation failed: INSTALL_PARSE_FAILED_NO_CERTIFICATES

**Comment by FICTURE7** [comment] 2016-02-07 06:58
If you're using the winrar method, yes you do need to resign the apk.

**Comment by FICTURE7** [comment] 2016-02-07 08:55
Everything seems to be working fine, so I guess I can close this.

**Closed as completed by FICTURE7** 2016-02-07 08:55 UTC
